config/routes.rb
Rails.application.routes.draw do
  resources :harbors
  resources :itineraries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/harbor.rb
class Harbor < ApplicationRecord
end

app/models/itinerary.rb
class Itinerary < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/harbors_controller.rb
class HarborsController < ApplicationController
  before_action :set_harbor, only: [:show, :edit, :update, :destroy]

  # GET /harbors
  # GET /harbors.json
  def index
    @harbors = Harbor.all
  end

  # GET /harbors/1
  # GET /harbors/1.json
  def show
  end

  # GET /harbors/new
  def new
    @harbor = Harbor.new
  end

  # GET /harbors/1/edit
  def edit
  end

  # POST /harbors
  # POST /harbors.json
  def create
    @harbor = Harbor.new(harbor_params)

    respond_to do |format|
      if @harbor.save
        format.html { redirect_to @harbor, notice: 'Harbor was successfully created.' }
        format.json { render :show, status: :created, location: @harbor }
      else
        format.html { render :new }
        format.json { render json: @harbor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /harbors/1
  # PATCH/PUT /harbors/1.json
  def update
    respond_to do |format|
      if @harbor.update(harbor_params)
        format.html { redirect_to @harbor, notice: 'Harbor was successfully updated.' }
        format.json { render :show, status: :ok, location: @harbor }
      else
        format.html { render :edit }
        format.json { render json: @harbor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /harbors/1
  # DELETE /harbors/1.json
  def destroy
    @harbor.destroy
    respond_to do |format|
      format.html { redirect_to harbors_url, notice: 'Harbor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_harbor
      @harbor = Harbor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def harbor_params
      params.require(:harbor).permit(:longitude, :latitude, :start_time, :end_time, :name, :commune, :capacity)
    end
end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
  before_action :set_itinerary, only: [:show, :edit, :update, :destroy]

  # GET /itineraries
  # GET /itineraries.json
  def index
    @itineraries = Itinerary.all
  end

  # GET /itineraries/1
  # GET /itineraries/1.json
  def show
  end

  # GET /itineraries/new
  def new
    @itinerary = Itinerary.new
  end

  # GET /itineraries/1/edit
  def edit
  end

  # POST /itineraries
  # POST /itineraries.json
  def create
    @itinerary = Itinerary.new(itinerary_params)

    respond_to do |format|
      if @itinerary.save
        format.html { redirect_to @itinerary, notice: 'Itinerary was successfully created.' }
        format.json { render :show, status: :created, location: @itinerary }
      else
        format.html { render :new }
        format.json { render json: @itinerary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /itineraries/1
  # PATCH/PUT /itineraries/1.json
  def update
    respond_to do |format|
      if @itinerary.update(itinerary_params)
        format.html { redirect_to @itinerary, notice: 'Itinerary was successfully updated.' }
        format.json { render :show, status: :ok, location: @itinerary }
      else
        format.html { render :edit }
        format.json { render json: @itinerary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /itineraries/1
  # DELETE /itineraries/1.json
  def destroy
    @itinerary.destroy
    respond_to do |format|
      format.html { redirect_to itineraries_url, notice: 'Itinerary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_itinerary
      @itinerary = Itinerary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def itinerary_params
      params.require(:itinerary).permit(:origin, :destiny, :departure_time, :arrival_time, :ship, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/harbors_helper.rb
module HarborsHelper
end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
end

app/views/harbors/_form.html.erb
<%= form_for(harbor) do |f| %>
  <% if harbor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(harbor.errors.count, "error") %> prohibited this harbor from being saved:</h2>

      <ul>
      <% harbor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :start_time %>
    <%= f.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= f.label :end_time %>
    <%= f.datetime_select :end_time %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :commune %>
    <%= f.text_field :commune %>
  </div>

  <div class="field">
    <%= f.label :capacity %>
    <%= f.number_field :capacity %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/harbors/edit.html.erb
<h1>Editing Harbor</h1>

<%= render 'form', harbor: @harbor %>

<%= link_to 'Show', @harbor %> |
<%= link_to 'Back', harbors_path %>

app/views/harbors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Harbors</h1>

<table>
  <thead>
    <tr>
      <th>Longitude</th>
      <th>Latitude</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Name</th>
      <th>Commune</th>
      <th>Capacity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @harbors.each do |harbor| %>
      <tr>
        <td><%= harbor.longitude %></td>
        <td><%= harbor.latitude %></td>
        <td><%= harbor.start_time %></td>
        <td><%= harbor.end_time %></td>
        <td><%= harbor.name %></td>
        <td><%= harbor.commune %></td>
        <td><%= harbor.capacity %></td>
        <td><%= link_to 'Show', harbor %></td>
        <td><%= link_to 'Edit', edit_harbor_path(harbor) %></td>
        <td><%= link_to 'Destroy', harbor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Harbor', new_harbor_path %>

app/views/harbors/new.html.erb
<h1>New Harbor</h1>

<%= render 'form', harbor: @harbor %>

<%= link_to 'Back', harbors_path %>

app/views/harbors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Longitude:</strong>
  <%= @harbor.longitude %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @harbor.latitude %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @harbor.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @harbor.end_time %>
</p>

<p>
  <strong>Name:</strong>
  <%= @harbor.name %>
</p>

<p>
  <strong>Commune:</strong>
  <%= @harbor.commune %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @harbor.capacity %>
</p>

<%= link_to 'Edit', edit_harbor_path(@harbor) %> |
<%= link_to 'Back', harbors_path %>

app/views/itineraries/_form.html.erb
<%= form_for(itinerary) do |f| %>
  <% if itinerary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(itinerary.errors.count, "error") %> prohibited this itinerary from being saved:</h2>

      <ul>
      <% itinerary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :origin %>
    <%= f.text_field :origin %>
  </div>

  <div class="field">
    <%= f.label :destiny %>
    <%= f.text_field :destiny %>
  </div>

  <div class="field">
    <%= f.label :departure_time %>
    <%= f.datetime_select :departure_time %>
  </div>

  <div class="field">
    <%= f.label :arrival_time %>
    <%= f.datetime_select :arrival_time %>
  </div>

  <div class="field">
    <%= f.label :ship %>
    <%= f.text_field :ship %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.number_field :status %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/itineraries/edit.html.erb
<h1>Editing Itinerary</h1>

<%= render 'form', itinerary: @itinerary %>

<%= link_to 'Show', @itinerary %> |
<%= link_to 'Back', itineraries_path %>

app/views/itineraries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Itineraries</h1>

<table>
  <thead>
    <tr>
      <th>Origin</th>
      <th>Destiny</th>
      <th>Departure time</th>
      <th>Arrival time</th>
      <th>Ship</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @itineraries.each do |itinerary| %>
      <tr>
        <td><%= itinerary.origin %></td>
        <td><%= itinerary.destiny %></td>
        <td><%= itinerary.departure_time %></td>
        <td><%= itinerary.arrival_time %></td>
        <td><%= itinerary.ship %></td>
        <td><%= itinerary.status %></td>
        <td><%= link_to 'Show', itinerary %></td>
        <td><%= link_to 'Edit', edit_itinerary_path(itinerary) %></td>
        <td><%= link_to 'Destroy', itinerary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Itinerary', new_itinerary_path %>

app/views/itineraries/new.html.erb
<h1>New Itinerary</h1>

<%= render 'form', itinerary: @itinerary %>

<%= link_to 'Back', itineraries_path %>

app/views/itineraries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Origin:</strong>
  <%= @itinerary.origin %>
</p>

<p>
  <strong>Destiny:</strong>
  <%= @itinerary.destiny %>
</p>

<p>
  <strong>Departure time:</strong>
  <%= @itinerary.departure_time %>
</p>

<p>
  <strong>Arrival time:</strong>
  <%= @itinerary.arrival_time %>
</p>

<p>
  <strong>Ship:</strong>
  <%= @itinerary.ship %>
</p>

<p>
  <strong>Status:</strong>
  <%= @itinerary.status %>
</p>

<%= link_to 'Edit', edit_itinerary_path(@itinerary) %> |
<%= link_to 'Back', itineraries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShowNNTell</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>